import { siteConfig } from "@/config/site";

export default function Component() {
	return (
		<div className="max-w-4xl mx-auto p-6 space-y-8">
			<header className="space-y-2">
				<h1 className="text-3xl font-bold">Privacy Policy</h1>
				<p className="text-sm text-gray-500">Last updated: October 20, 2024</p>
			</header>

			<section className="space-y-4">
				<p>
					This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of
					Your information when You use the Service and tells You about Your privacy rights and how the law
					protects You.
				</p>
				<p>
					We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
					collection and use of information in accordance with this Privacy Policy. This Privacy Policy has
					been created with the help of the{" "}
					<a
						href="https://www.termsfeed.com/privacy-policy-generator/"
						target="_blank"
						rel="noopener noreferrer"
						className="text-blue-600 hover:underline"
					>
						Privacy Policy Generator
					</a>
					.
				</p>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
				<h3 className="text-xl font-semibold">Interpretation</h3>
				<p>
					The words of which the initial letter is capitalized have meanings defined under the following
					conditions. The following definitions shall have the same meaning regardless of whether they appear
					in singular or in plural.
				</p>
				<h3 className="text-xl font-semibold">Definitions</h3>
				<p>For the purposes of this Privacy Policy:</p>
				<ul className="list-disc pl-6 space-y-2">
					<li>
						<strong>Account</strong> means a unique account created for You to access our Service or parts
						of our Service.
					</li>
					<li>
						<strong>Affiliate</strong> means an entity that controls, is controlled by or is under common
						control with a party, where &quot;control&quot; means ownership of 50% or more of the shares,
						equity interest or other securities entitled to vote for election of directors or other managing
						authority.
					</li>
					<li>
						<strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
						&quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to
						remix-shadcn-supabase-boilerplate.
					</li>
					<li>
						<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
						other device by a website, containing the details of Your browsing history on that website among
						its many uses.
					</li>
					<li>
						<strong>Country</strong> refers to: United Kingdom
					</li>
					<li>
						<strong>Device</strong> means any device that can access the Service such as a computer, a
						cellphone or a digital tablet.
					</li>
					<li>
						<strong>Personal Data</strong> is any information that relates to an identified or identifiable
						individual.
					</li>
					<li>
						<strong>Service</strong> refers to the Website.
					</li>
					<li>
						<strong>Service Provider</strong> means any natural or legal person who processes the data on
						behalf of the Company. It refers to third-party companies or individuals employed by the Company
						to facilitate the Service, to provide the Service on behalf of the Company, to perform services
						related to the Service or to assist the Company in analyzing how the Service is used.
					</li>
					<li>
						<strong>Usage Data</strong> refers to data collected automatically, either generated by the use
						of the Service or from the Service infrastructure itself (for example, the duration of a page
						visit).
					</li>
					<li>
						<strong>Website</strong> refers to remix-shadcn-supabase-boilerplate, accessible from{" "}
						<a
							href={siteConfig.url}
							rel="external nofollow noopener noreferrer"
							target="_blank"
							className="text-blue-600 hover:underline"
						>
							{siteConfig.url}
						</a>
					</li>
					<li>
						<strong>You</strong> means the individual accessing or using the Service, or the company, or
						other legal entity on behalf of which such individual is accessing or using the Service, as
						applicable.
					</li>
				</ul>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
				<h3 className="text-xl font-semibold">Types of Data Collected</h3>
				<h4 className="text-lg font-semibold">Personal Data</h4>
				<p>
					While using Our Service, We may ask You to provide Us with certain personally identifiable
					information that can be used to contact or identify You. Personally identifiable information may
					include, but is not limited to:
				</p>
				<ul className="list-disc pl-6">
					<li>Email address</li>
					<li>Usage Data</li>
				</ul>
				<h4 className="text-lg font-semibold">Usage Data</h4>
				<p>Usage Data is collected automatically when using the Service.</p>
				<p>
					Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP
					address), browser type, browser version, the pages of our Service that You visit, the time and date
					of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
				</p>
				<p>
					When You access the Service by or through a mobile device, We may collect certain information
					automatically, including, but not limited to, the type of mobile device You use, Your mobile device
					unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
					Internet browser You use, unique device identifiers and other diagnostic data.
				</p>
				<p>
					We may also collect information that Your browser sends whenever You visit our Service or when You
					access the Service by or through a mobile device.
				</p>
				<h4 className="text-lg font-semibold">Tracking Technologies and Cookies</h4>
				<p>
					We use Cookies and similar tracking technologies to track the activity on Our Service and store
					certain information. Tracking technologies used are beacons, tags, and scripts to collect and track
					information and to improve and analyze Our Service. The technologies We use may include:
				</p>
				<ul className="list-disc pl-6 space-y-2">
					<li>
						<strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You
						can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.
						However, if You do not accept Cookies, You may not be able to use some parts of our Service.
						Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may
						use Cookies.
					</li>
					<li>
						<strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small
						electronic files known as web beacons (also referred to as clear gifs, pixel tags, and
						single-pixel gifs) that permit the Company, for example, to count users who have visited those
						pages or opened an email and for other related website statistics (for example, recording the
						popularity of a certain section and verifying system and server integrity).
					</li>
				</ul>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Children's Privacy</h2>
				<p>
					Our Service does not address anyone under the age of 13. We do not knowingly collect personally
					identifiable information from anyone under the age of 13. If You are a parent or guardian and You
					are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware
					that We have collected Personal Data from anyone under the age of 13 without verification of
					parental consent, We take steps to remove that information from Our servers.
				</p>
				<p>
					If We need to rely on consent as a legal basis for processing Your information and Your country
					requires consent from a parent, We may require Your parent's consent before We collect and use that
					information.
				</p>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Links to Other Websites</h2>
				<p>
					Our Service may contain links to other websites that are not operated by Us. If You click on a third
					party link, You will be directed to that third party's site. We strongly advise You to review the
					Privacy Policy of every site You visit.
				</p>
				<p>
					We have no control over and assume no responsibility for the content, privacy policies or practices
					of any third party sites or services.
				</p>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Changes to this Privacy Policy</h2>
				<p>
					We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the
					new Privacy Policy on this page.
				</p>
				<p>
					We will let You know via email and/or a prominent notice on Our Service, prior to the change
					becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
				</p>
				<p>
					You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
					Policy are effective when they are posted on this page.
				</p>
			</section>

			<section className="space-y-4">
				<h2 className="text-2xl font-semibold">Contact Us</h2>
				<p>If you have any questions about this Privacy Policy, You can contact us:</p>
				<ul className="list-disc pl-6">
					<li>By email: {siteConfig.contactEmail}</li>
				</ul>
			</section>
		</div>
	);
}
